spring:
  security:
    user:
      name: admin
      password: 123

  output:
    ansi:
      enabled: ALWAYS
server:
  port: 8090

flink:
  pipeline-name: flinkCDCTest
  batchProcessingDataCount: 14184
  parallelism: 6
  batchSize: 2000
  mysqlDataSource:
    - port: 3307
      hostname: 127.0.0.1
      databaseList:
        - mydb
      tableList:
        - mydb.orders
      username: root
      password: 123456

databricks:

